### PR TITLE
Changed vector access from public to private

### LINKED ISSUE #17: Make Vector propetries private
For classes `Vector3`, `Vector3f`, `Vector2`, `Vector2f`, `Position`, `Location` make all properties private.

----

Example:

Original:
```java
public class Vector {

  public double x, y, x;

  //...
}
```

Result:
```java
public class Vector {

  private double x, y, x;

  public double x() {
    return x;
  }

  public double y() {
    return y;
  }

  public double z() {
    return z;
  }

  //...
}
```

### PR DESCRIPTION
**Pull request by KoshakMineDEV**

### CODE REVIEW

**Review by ScarletRedMan — CHANGES_REQUESTED** [review]
Make yaw and pitch properties private

**Review by ScarletRedMan — CHANGES_REQUESTED** [review]
Field `level` must be private property in `Location`

**Comment by KoshakMineDEV** [comment]
@ScarletRedMan I hate u bro

**Comment by ScarletRedMan** [comment]
> @ScarletRedMan I hate u bro

But you need to resolve merge conflicts

**Review by ScarletRedMan — APPROVED** [review]

**Pull request merged**
